version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: cspell-dmenu
    path: ./.config/cspell-dmenu.txt
    addWords: true
dictionaries:
  - cspell-dmenu
words: []
ignoreWords: []
import: []
