version: "3"

env:
  VERSION: "0.1.0"

tasks:
  default:
    cmds:
      - task: build

  setup:
    cmds:
      - rustup update
      - cargo install --force --version "0.7.0" rust-script
      - cargo install --force --version "0.37.11" cargo-make
    silent: false

  build:
    deps: [setup]
    cmds:
      - task: build-plain
      - echo 'Finished building "dmenu-rs" project.'

  build-plain:
    cmds:
      - cmd: cargo make --profile release -- build

  create-bundle:
    deps:
      - setup
    cmds:
      - cargo make create-bundle --profile release
